#!/bin/bash

declare -a tests=("change" "condvar" "donate-chain" "donate-lower" "donate-multiple2" "donate-multiple" "donate-nest" "donate-one" "donate-sema" "fifo" "preempt" "sema")

if [ ! -d "build" ]; then
	make
fi

rm build/tests/threads/priority-*.result

for t in "${tests[@]}"
do
	make build/tests/threads/priority-$t.result
done
